poly1305/asm/poly1305-armv4.pl: fix Clang compatibility issue
I.e.:

    error: out of range immediate fixup value

This fix is identical to one of the changes made in 3405db9, which I
discovered right after taking a quick stab at fixing this.

CLA: trivial
Fixes #7878

Reviewed-by: Kurt Roeckx <kurt@roeckx.be>
Reviewed-by: Tomas Mraz <tmraz@fedoraproject.org>
(Merged from https://github.com/openssl/openssl/pull/13757)

(cherry picked from commit a953f26dba5dadf8ac69c6fcbf71ebe3efba9407)